<script setup>
import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';
import api, { apiError } from '../services/api';
import ErrorAlert from '../components/ErrorAlert.vue';
import LoadingState from '../components/LoadingState.vue';

const route = useRoute(); const course = ref(null); const lecturers = ref([]); const candidates = ref([]); const selected = ref([]); const loading = ref(true); const error = ref('');
async function load() { loading.value = true; try { const [c, l, s] = await Promise.all([api.get(`/admin/courses/${route.params.id}`), api.get('/admin/lecturers'), api.get('/admin/students')]); course.value = c.data.data; lecturers.value = l.data.data; candidates.value = s.data.data; } catch (e) { error.value = apiError(e).message; } finally { loading.value = false; } }
async function save() { try { await api.put(`/admin/courses/${course.value.id}`, { code: course.value.code, title: course.value.title, description: course.value.description, is_active: course.value.is_active, lecturer_id: course.value.lecturer.id }); await load(); } catch (e) { error.value = apiError(e).message; } }
async function enroll() { try { await api.post(`/admin/courses/${course.value.id}/students`, { student_ids: selected.value.map(Number) }); selected.value = []; await load(); } catch (e) { error.value = apiError(e).message; } }
async function remove(student) { if (!confirm('Remove this student from the course?')) return; try { await api.delete(`/admin/courses/${course.value.id}/students/${student.id}`); await load(); } catch (e) { error.value = apiError(e).message; } }
onMounted(load);
</script>
<template><section class="space-y-6"><RouterLink class="text-indigo-600" to="/admin/courses">← Courses</RouterLink><ErrorAlert :message="error" @dismiss="error = ''"/><LoadingState v-if="loading" label="Loading course…"/><template v-else-if="course"><h1 class="text-3xl font-black">{{ course.code }} · {{ course.title }}</h1><div class="grid gap-6 lg:grid-cols-2"><form class="card space-y-3" @submit.prevent="save"><input v-model="course.code" class="field"><input v-model="course.title" class="field"><textarea v-model="course.description" class="field"></textarea><select v-model="course.lecturer.id" class="field"><option v-for="lecturer in lecturers" :key="lecturer.id" :value="lecturer.id">{{ lecturer.name }}</option></select><label class="flex gap-2"><input v-model="course.is_active" type="checkbox"> Active course</label><button class="btn-primary">Save course</button></form><form class="card space-y-3" @submit.prevent="enroll"><h2 class="font-black">Enroll students</h2><select v-model="selected" class="field min-h-40" multiple required><option v-for="student in candidates" :key="student.id" :value="student.id">{{ student.name }}</option></select><button class="btn-primary">Enroll selected</button></form></div><div class="card"><h2 class="font-black">Enrolled students</h2><p v-if="!course.students?.length" class="mt-3 text-slate-500">No students enrolled.</p><div v-for="student in course.students" :key="student.id" class="flex justify-between border-t py-3"><span>{{ student.name }}</span><button class="text-rose-600" @click="remove(student)">Remove</button></div></div></template></section></template>
